### ISSUE TITLE
run CDC need CDCMarketUpdate class

### ISSUE THREAD

**Issue by jiadongpo** [pushtechnology/adapters#1]
I want to run CDC to extract  data from informix，but CDCConnection class has CDCMarketUpdate class，I can't  find ! Can you help me! thanks very much.

**Comment by freddiecoleman** [comment]
The CDCMarketUpdate class contained within the Javadoc is just example code and is not supplied. You should modify the example code to meet your requirements.

**Comment by jiadongpo** [comment]
Got it. Thank you very much for your reply. Thank you!
